from prettyconf import config

SENDGRID_APIKEY = config('SENDGRID_APIKEY')
SENDGRID_FROM_EMAIL = config('SENDGRID_FROM_EMAIL')
SENDGRID_FROM_NAME = config('SENDGRID_FROM_NAME')
GANALYTICS_TRACKING_ID = config('GANALYTICS_TRACKING_ID')
